version: '3.6'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"
      - "5000:5000"
    extra_hosts:
      - "dockerhost:IP_DA_MAQUINA_COM_TOMCAT"
  tomcat:
    image: tomcat:8.0-jre8
    container_name: tomcat
    restart: always
    volumes:
      - "/opt/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
    ports:
      - "8080:8080"
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - certs-data:/data/letsencrypt
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "tomcathost:IP_DA_MAQUINA_COM_TOMCAT"
    environment:
    - DOMAIN:dominio.com
volumes:
  certs:
  certs-data:
